const pathfinderConditions = [
  'Blinded',
  'Broken',
  'Clumsy',
  'Concealed',
  'Confused',
  'Controlled',
  'Dazzled',
  'Deafened',
  'Doomed',
  'Drained',
  'Dying',
  'Encumbered',
  'Enfeebled',
  'Fascinated',
  'Fatigued',
  'Fleeing',
  'Friendly',
  'Frightened',
  'Grabbed',
  'Helpful',
  'Hidden',
  'Hostile',
  'Immobilized',
  'Indifferent',
  'Invisible',
  'Observed',
  'Off-guard',
  'Paralyzed',
  'Persistent Damage',
  'Petrified',
  'Prone',
  'Quickened',
  'Restrained',
  'Sickened',
  'Slowed',
  'Stunned',
  'Stupefied',
  'Unconscious',
  'Undetected',
  'Unfriendly',
  'Unnoticed',
  'Wounded',
]

export default pathfinderConditions
